#! /bin/zsh
#===================================================================
#
#
#   ██╗  ██╗██╗██╗  ██╗██╗███████╗██████╗  █████╗ 
#   ╚██╗██╔╝╚═╝███╗ ██║╚═╝╚═██╔══╝██╔══██╗██╔══██╗
#    ╚███╔╝ ██╗███████║██╗  ██║   ██████╔╝██║  ╚═╝
#    ██╔██╗ ██║██╔═███║██║  ██║   ██╔══██╗██║  ██╗
#   ██╔╝╚██╗██║██║ ╚██║██║  ██║   ██║  ██║╚█████╔╝
#   ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝  ╚═╝ ╚════╝ 
#
#
# 	.xinitrc configuration by adipopbv (adi.pop.bv@gmail.com).
# 	~/.xinitrc - X11's xinit sourced file (WM, graphical stuff etc).
# 	Go to https://wiki.archlinux.org/index.php/Xinit for more info.
#
#
#===================================================================

# Start optimus prime offloading
/usr/bin/prime-offload

# Start i3 session (needs to be last)
exec i3

